services:
  vllm:
      image: vllm/vllm-openai:latest
      container_name: vllm-qwen3
      restart: unless-stopped
      ports:
        - "8001:8001"
      volumes:
        - ./cache/:/root/.cache/
      environment:
        - HF_HOME=/root/.cache/huggingface
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      command: >
        vllm serve Qwen/Qwen3-30B-A3B-Instruct-2507
        --port 8001
        --quantization fp8
        --gpu-memory-utilization 0.5
  speech-to-speech:
    container_name: speech-to-speech
    build:
      context: .
      dockerfile: Dockerfile
    command: 
        - speech-to-speech
        - --mode
        - realtime
        - --stt
        - parakeet-tdt
        - --language
        - auto
        - --llm_backend
        - responses-api
        - --model_name
        - Qwen/Qwen3-30B-A3B-Instruct-2507
        - --responses_api_base_url
        - http://localhost:8001/v1
        - --responses_api_api_key
        - dummy
        - --responses_api_stream
        - "false"
        - --tts
        - pocket
        - --pocket_tts_voice
        - azelma
        - --pocket_tts_device
        - cpu
      # - --tts
      # - qwen3
      # - --qwen3_tts_model_name
      # - Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
      # - --enable_live_transcription
    ports:
      - "8765:8765"
    volumes:
      - ./cache/:/root/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]