services:
  speech-to-speech:
    container_name: speech-to-speech
    build:
      context: .
      dockerfile: Dockerfile
    command: 
      - speech-to-speech
      - --mode
      - realtime
      - --stt
      - openai/whisper-large-v3
      # - parakeet-tdt
      - --llm_backend
      - transformers
      - --model_name
      # - openai/gpt-oss-20b
      # - Qwen/Qwen3-14B --> a bit slow
      - Qwen/Qwen3-8B
      - --tts
      - qwen3
      - --qwen3_tts_model_name
      - Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
      - --enable_live_transcription
    ports:
      - "8765:8765"
    volumes:
      - ./cache/:/root/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]